apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.demo.ownid.com
            - name: OWNID__DID
              value: did:ownid:demo
            - name: OWNID__NAME
              value: OwnID Demo
            - name: OWNID__DESCRIPTION
              value: OwnID Demo
            - name: OWNID__PUB_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: public_key
            - name: OWNID__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: private_key
            - name: OWNID__TFA_ENABLED
              value: 'false'
            - name: OWNID__FIDO2_FALLBACK_BEHAVIOR
              value: Basic
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: demo.ownid.com
            - name: GIGYA__DATA_CENTER
              value: us1.gigya.com
            - name: GIGYA__SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: gigya_secret
            - name: GIGYA__API_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-secret
                  key: gigya_api_key
            - name: Metrics__Enable
              value: 'true'
            - name: Metrics__Namespace
              value: 'Demo Production'
            - name: SMTP__HOST
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: host
            - name: SMTP__USER_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: user-name
            - name: SMTP__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: password
            - name: SMTP__SSL
              value: 'true'
            - name: SMTP__FROM_ADDRESS
              value: no-reply@skipthepassword.com
            - name: SMTP__FROM_NAME
              value: Magic Link
            - name: OWNID__MAGIC_LINK__ENABLED
              value: 'true'
            - name: OWNID__MAGIC_LINK__REDIRECT_URL
              value: https://demo.ownid.com/login