apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.demo-screens.dev.ownid.com
            - name: OWNID__DID
              value: did:ownid:demo_dev_screens_151850889514
            - name: OWNID__NAME
              value: Screens (OwnID Demo)
            - name: OWNID__DESCRIPTION
              value: Screens (OwnID Demo)
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo-screens.dev.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: demo-screens.dev.ownid.com
            - name: OWNID__MAGIC_LINK__ENABLED
              value: 'true'
            - name: OWNID__MAGIC_LINK__REDIRECT_URL
              value: https://demo-screens.dev.ownid.com
            - name: GIGYA__DATA_CENTER
              value: us1.gigya.com
            - name: GIGYA__SECRET
              valueFrom:
                secretKeyRef:
                  name: demo-screens-secret
                  key: gigya_secret
            - name: GIGYA__API_KEY
              valueFrom:
                secretKeyRef:
                  name: demo-screens-secret
                  key: gigya_api_key