dist: bionic
language: csharp
mono: none
dotnet: 3.1
script:
- dotnet restore
- dotnet test
- dotnet restore
notifications:
  slack:
    rooms:
      secure: Q/dBFI5fjwuRERL1yyUuWXgMR7ZmhCVaSDV4dtNaC8I1Zbngb2yePpe7J60TpwRDsYa/iT1oB464Ciezkjb3CSCU/IPUisyorOFlOTD2x6Z7AhM08M2vMGtQTa3OfgbuejspdHFNjI86Ti3ciyvIvJdEh69J/NkCUsxO7R3s/+mL6yxfiyU3M76btydOjuGd4YXwiigO9ovWmzCA3QiEY9BKApNuLag5bmRNVy1EdFUo/HQf2joLnAsOnvDusEQY1OcxXprsjFUVIJ/uVI1q//ZdhmfgaLRBsC66hW9n4Gh0Qb5uFhDysxOHY0EHF9dsoMKVhYWmSejOqbjvBQrEiGm75yPQKKSN9VZJq9HVRCW0KOH1oZTYa9oJoyiIpY0kYkEsN4KxrYnYP1XbL89neWN3OZROVu7n5p/pSNb3spjTJCg+HXYQ0Td5cLatSaUtPBum81MAJjAv8N72YArwXG4dnWmmxSBGWj8S6ozakmXnWThFFXd817dGzrbqtasjXEFM5EgTW83ptv35nzpHyRy5QWuMmNAfyoRYudSKdUk0T/UTNYZltv7M1NsWJEx/q9N3A4A4w/FOLNWT9YnHRrWhEi6sSQjam7X2d2j/UAgHT8+0vCY8uV76d+FZtQil+X8a6gMnCkJkwySUQI3MfV+LtlfTV6f4MEAE3VpIVqM=
    on_success: never
    on_failure: always
