sudo: true
notifications:
  slack:
    rooms:
      secure: Q/dBFI5fjwuRERL1yyUuWXgMR7ZmhCVaSDV4dtNaC8I1Zbngb2yePpe7J60TpwRDsYa/iT1oB464Ciezkjb3CSCU/IPUisyorOFlOTD2x6Z7AhM08M2vMGtQTa3OfgbuejspdHFNjI86Ti3ciyvIvJdEh69J/NkCUsxO7R3s/+mL6yxfiyU3M76btydOjuGd4YXwiigO9ovWmzCA3QiEY9BKApNuLag5bmRNVy1EdFUo/HQf2joLnAsOnvDusEQY1OcxXprsjFUVIJ/uVI1q//ZdhmfgaLRBsC66hW9n4Gh0Qb5uFhDysxOHY0EHF9dsoMKVhYWmSejOqbjvBQrEiGm75yPQKKSN9VZJq9HVRCW0KOH1oZTYa9oJoyiIpY0kYkEsN4KxrYnYP1XbL89neWN3OZROVu7n5p/pSNb3spjTJCg+HXYQ0Td5cLatSaUtPBum81MAJjAv8N72YArwXG4dnWmmxSBGWj8S6ozakmXnWThFFXd817dGzrbqtasjXEFM5EgTW83ptv35nzpHyRy5QWuMmNAfyoRYudSKdUk0T/UTNYZltv7M1NsWJEx/q9N3A4A4w/FOLNWT9YnHRrWhEi6sSQjam7X2d2j/UAgHT8+0vCY8uV76d+FZtQil+X8a6gMnCkJkwySUQI3MfV+LtlfTV6f4MEAE3VpIVqM=
    on_success: never
    on_failure: always

env:
  global:
  - secure: am3WB67aY9pj6ukZWu3KprFcge89kO8R1cn9+473u5bBaXZPzItc2vUZ8hdA6wpRwkZM6+qBggmgFBYWHP2y3aIBwG4cczdqXdGSGtYn0AlyDdEuMY/v0nHtxITieO2bo5kTPIPF0GOcc87ZO7m36F/5pNeG8ykE9/z4V3glemfB5RIwShdl0ZY7AgImn+3dOqCqFLZRk2H9MT0evJupGAbvE3R+nAwEr+JM3rBnpSn8Yzy+LHRHuVuKq0WICNRPZ2Q+kp0LVtPZH4r/T6Fi2SMjYCX9+31+5sP2jBL07V5mikFwBN5jATXdXcprgTQkmjbVMvCgsezVvTIcOa0l/HiGt5HQI+RnESzJaSlejr+yh7OwY+7OIDWJKX9p8EUBEHpOjhg8a+w46O0tzQiVQQXSZgTc1pjsnLuh2ezx47sC2cpilYn6dpcgtwR7YID/OWPQOPsZiuQ1bj67BHnMmI5JdiyYLQbWuyqB7R0UH+B8cQc4kJKOYK8fTrz1z4sdykfexbcrUcaY85wQr+g3wggnqL59edqFa39ctdHo18g8X5tV2bbaElLeACnfGeo57nJ6DCvHpZmff+FgIDvDZWLQG0+SF31yj5LBxEbQ3BIuuVyoaO10mMLs/9e9TO6G1Rzerc2/12NK6P7AM8gqYloKiF8f4VRFSDWxgy2fb3c=
  - secure: Dg7nv0ymO5pPVZFFyqjD2wajouRuwem8E0qt58mzPZ7zqPRD3xDEAAINXTU/S6qlq2G2ug0VcYNHLPVY7YtVRU13gjgiUkwXJSkIp7RskIbT/gTXi4qbHDxQiYhoS/OQCn/bNK6IrcMkVXxWpuZW7P+yLm10taZnrHb4+cdnhu2BbtY4DPPyzguZC6uOZtlNxpZiqXKp3now13XP1cyrPvXLRueWOSGA1Cmys4Yx30MrKER50Xse7A222XTxd409ntxO1cfhVNKAAoBlqY+mEQuNh9Q1YBPpjz/AbuYewuuQf1ssuBmpz0XGPjfwzwOLz+wusqzoKMyM1uoSsIjb4IiQqddi3X5ZRmoPD3ej86azgv5ASBzjkNvIEArTHkBwX+dt3Q0pueICznRf9W4gmV9Te7SZt8ke29z2UHZLqqlwqqsUWYnp8Cn9JH0I4DKpswkwyo/YC6DSWWETXM6siuJXiywTZLljV93xVEORNiU4/LUaosBgff3E6EXJHPzFLoJZTNyKbhUMWlPDCB2OTvrkAGTaM20xrlSEnm5lxkzCKGaki38lSIzf8IBQLkcTa0Ohs53Gw/WKktTdrw5vGKBdnWRCBTuU4aLNX2vF0oMYP2XqJMHwNhmNJ2qIC26HJluI4ZYS9mBg/Dg3eCF9wJlZDh3haHLBBNVLNdgRz34=

branches:
  only:
  - master
  - develop

dist: bionic
language: csharp
mono: none
dotnet: 3.1

script:
  - dotnet restore
  - dotnet test /p:CollectCoverage=true /p:Threshold=20
  - dotnet build

before_deploy:
  - pyenv global 3.7.1
  - pip install -U pip
  - pip install awscli
  - aws --version
  - sudo apt-get install libxml2-utils

deploy:
- provider: script
  script: sh scripts/publish.sh dev
  skip_cleanup: true
  on:
    branch: develop
- provider: script
  script: sh scripts/publish.sh staging
  skip_cleanup: true
  on:
    branch: master