apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownid-server
spec:
  template:
    spec:
      containers:
        - name: ownid-server # (1)
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: prod
            - name: OWNID__CACHE_TYPE
              value: redis
            - name: OWNID__CACHE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: redis_config
            - name: ELASTICCONFIGURATION__ENABLED
              value: 'true'
            - name: ELASTICCONFIGURATION__URI
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: elastic_uri
            - name: ELASTICCONFIGURATION__USERNAME
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: elastic_username
            - name: ELASTICCONFIGURATION__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: elastic_password
            - name: AWS__Region
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: region
            - name: AWS__AccessKeyId
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: access_key_id
            - name: AWS__SecretAccessKey
              valueFrom:
                secretKeyRef:
                  name: aws-secret
                  key: secret_access_key