apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-server
spec:
  template:
    spec:
      containers:
        - name: single-server
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.dor.ownid.com
            - name: OWNID__DID
              value: did:ownid:dor_staging_151850889514
            - name: OWNID__NAME
              value: OwnID (Dor's server)
            - name: OWNID__DESCRIPTION
              value: OwnID (Dor's server)
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo.staging.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: dor.ownid.com
            - name: OWNID__MAGIC_LINK__ENABLED
              value: 'true'
            - name: OWNID__MAGIC_LINK__REDIRECT_URL
              value: https://gigya.single.demo.staging.ownid.com/login
            - name: SERVER_MODE
              value: pilot
            - name: GIGYA__DATA_CENTER
              value: eu1.gigya.com
            - name: GIGYA__SECRET
              valueFrom:
                secretKeyRef:
                  name: dor-secret
                  key: gigya_secret
            - name: GIGYA__API_KEY
              valueFrom:
                secretKeyRef:
                  name: dor-secret
                  key: gigya_api_key
            - name: GIGYA__USER_KEY
              valueFrom:
                secretKeyRef:
                  name: dor-secret
                  key: gigya_user_key
            - name: OWNID__PUB_KEY
              valueFrom:
                secretKeyRef:
                  key: public_key
                  name: dor-secret
            - name: OWNID__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  key: private_key
                  name: dor-secret