apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-server
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__WEB_APP_URL
              value: https://sign.dev.ownid.com
            - name: ASPNETCORE_ENVIRONMENT
              value: dev
            - name: SMTP__HOST
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: host
            - name: SMTP__USER_NAME
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: user-name
            - name: SMTP__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: demo-smtp-secret
                  key: password
            - name: SMTP__SSL
              value: 'true'
            - name: SMTP__FROM_ADDRESS
              value: no-reply@skipthepassword.com
            - name: SMTP__FROM_NAME
              value: Magic Link - DEV
            