apiVersion: apps/v1
kind: Deployment
metadata:
  name: ownid-server
spec:
  template:
    spec:
      containers:
        - name: ownid-server # (1)
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.demo4.staging.ownid.com
            - name: OWNID__DID
              value: did:ownid:demo_4_staging_151850889514
            - name: OWNID__NAME
              value: Noted (OwnID Demo 4)
            - name: OWNID__DESCRIPTION
              value: Noted (OwnID Demo 4)
            - name: OWNID__AUTHENTICATION_MODE
              value: OwnIdOnly
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.demo4.staging.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: demo4.staging.ownid.com
