apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-gigya
spec:
  template:
    spec:
      containers:
        - name: server-gigya
          env:
            - name: OWNID__CALLBACK_URL
              value: https://server.roche-staging.ownid.com
            - name: OWNID__DID
              value: did:roche-staging:prod_822386385
            - name: OWNID__NAME
              value: Roche Staging
            - name: OWNID__DESCRIPTION
              value: Roche Staging Environment
            - name: OWNID__PUB_KEY
              valueFrom:
                secretKeyRef:
                  name: roche-staging-secret
                  key: public_key
            - name: OWNID__PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: roche-staging-secret
                  key: private_key
            - name: OWNID__FIDO2_PASSWORDLESS_PAGE_URL
              value: https://passwordless.roche-staging.ownid.com
            - name: OWNID__TOP_DOMAIN
              value: roche-staging.ownid.com
            - name: GIGYA__DATA_CENTER
              value: us1.gigya.com
            - name: GIGYA__SECRET
              valueFrom:
                secretKeyRef:
                  name: roche-staging-secret
                  key: gigya_secret
            - name: GIGYA__API_KEY
              valueFrom:
                secretKeyRef:
                  name: roche-staging-secret
                  key: gigya_api_key
            - name: GIGYA__USER_KEY
              valueFrom:
                secretKeyRef:
                  name: roche-staging-secret
                  key: gigya_user_key
            - name: SERVER_MODE
              value: pilot
            - name: Metrics__Enable
              value: 'true'
            - name: Metrics__Namespace
              value: 'roche-staging'
            - name: SERILOG__MINIMUMLEVEL__DEFAULT
              value: Debug