apiVersion: apps/v1
kind: Deployment
metadata:
  name: single-server
spec:
  revisionHistoryLimit: 1
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate