apiVersion: apps/v1
kind: Deployment
spec:
  revisionHistoryLimit: 1
  template:
    spec:
      containers:
        - name: server
          image: ownid.common.repositories.cloud.sap/server:latest
          ports:
            - containerPort: 5002
          env:
            - name: OWNID__CACHE_TYPE
              value: redis
            - name: OWNID__CACHE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: redis_config
            - name: ELASTICCONFIGURATION__ENABLED
              value: 'true'
            - name: ELASTICCONFIGURATION__URI
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: elastic_uri
            - name: ELASTICCONFIGURATION__USERNAME
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: elastic_username
            - name: ELASTICCONFIGURATION__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ownid-secrets
                  key: elastic_password