apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


patchesStrategicMerge:
- custom-env.yaml
- replica-and-rollout-strategy.yaml
- database-secret.yaml
resources:
- ../../base
images:
- name: foo/bar
  newName: ownid.common.repositories.cloud.sap/dev/server/ownid-server-gigya_1.0.942
  newTag: 895788ea062e7a5cfb1f2e8a33f6a4d30c3e7b2d
